sudo: false
language: ruby
before_install: gem install bundler
cache: bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.8
  - rvm: 2.4.5
  - rvm: 2.5.3
  - rvm: 2.6.0
  - rvm: ruby-head
  - rvm: jruby-head
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
script:
- bundle exec rspec
